main/routes/web.php
<?php
use Illuminate\Http\Request;
use App\User;
use App\AgentCustomer;
use App\Receiver;
use App\Transaction;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/  
 

Route::get('/payment/{type}/{id}/', ['as'=>'payments.pay', 'uses'=>'PaymentsController@pay']);
Route::get('/payment/part/user/{id}/{amount}', ['as'=>'payments.part_pay', 'uses'=>'PaymentsController@part_pay']);
Route::post('/paypal/payments', ['as'=>'payments.paypal', 'uses'=>'PaymentsController@paypal_store']);
Route::post('/paypal/strip', ['as'=>'payments.strip', 'uses'=>'PaymentsController@stripe_store']);
Route::get('status', 'PayPalController@getPaymentStatus');


Route::group(['middleware' =>'isLogin'], function(){

    Route::get('/message/{type}/{id}/validate_mobile', ['as'=>'message.validate_mobile', 'uses'=>'MessageController@validate_mobile']);
    
    Route::post('/mobile/confirm_code',  'MessageController@confirm_code');
 
     Route::get('/',['as'=>'members.home','uses'=>'UsersController@home']);
     
     Route::get('/home',['as'=>'members.home','uses'=>'UsersController@home']);

     Route::get('/currency/sender/{id}',['as'=>'currencies.sender','uses'=>'CurrenciesController@sender']);
       
 /*
    |--------------------------------------------------------------------------
    | Admin
    |--------------------------------------------------------------------------
     
            */
         Route::group(['middleware' =>'admin'], function(){
             /*
              |--------------------------------------------------------------------------
              | Payments 
              |--------------------------------------------------------------------------
          */
            Route::resource('payments', 'PaymentsController');
            Route::get('/{type}/user/payment', ['as'=>'payments.user_type', 'uses'=>'PaymentsController@user_type']);
            Route::post('/post_search/payment', ['as'=>'payments.post_search', 'uses'=>'PaymentsController@post_search']);
            /*
              |--------------------------------------------------------------------------
              | Subscription 
              |--------------------------------------------------------------------------
          */
          Route::resource('subscription', 'SubscriptionController');

                Route::resource('admin', 'AdminController');
                  /*
                    |--------------------------------------------------------------------------
                    | Subscription 
                    |--------------------------------------------------------------------------
                */
                Route::resource('subscription', 'SubscriptionController');

                /*
                    |--------------------------------------------------------------------------
                    | Rate 
                    |--------------------------------------------------------------------------
                */
                Route::resource('rate', 'RateController');

                   /*
                    |--------------------------------------------------------------------------
                    | Currencies 
                    |--------------------------------------------------------------------------
                */
                Route::resource('currencies', 'CurrenciesController');
                
                /*
                    |--------------------------------------------------------------------------
                    | Commission 
                    |--------------------------------------------------------------------------
                */
                Route::resource('commission', 'CommissionController');
                /*
                    |--------------------------------------------------------------------------
                    | Bank 
                    |--------------------------------------------------------------------------
                */
                Route::resource('bank', 'BankController');
                /*
                    |--------------------------------------------------------------------------
                    | Business Setup
                    |--------------------------------------------------------------------------
                */

                Route::resource('setup-business', 'SetupBusinessController');
                /*
                    |--------------------------------------------------------------------------
                    | Transaction Setup
                    |--------------------------------------------------------------------------
                */

                Route::resource('setup-transaction', 'SetupTransactionController');

        /*
                    |--------------------------------------------------------------------------
                    | Message
                    |--------------------------------------------------------------------------
         */

        Route::resource('message', 'MessageController');
        Route::get('/user/{id}/message', ['as'=>'message.user', 'uses'=>'MessageController@index']);

                
        /*
            |--------------------------------------------------------------------------
            | Payment 
            |--------------------------------------------------------------------------
         */
            
        Route::resource('partpayment', 'PartPaymentController');
        Route::get('/partpayment/{id}/agent/transactions', ['as'=>'partpayment.transactions', 'uses'=>'PartPaymentController@transactions']);
        Route::get('/partpayment/{id}/agent/commission', ['as'=>'partpayment.commissions', 'uses'=>'PartPaymentController@commissions']);
        Route::post('/post_search/partpayment', ['as'=>'partpayment.post_search', 'uses'=>'PartPaymentController@post_search']);
       
        
        /*
            |--------------------------------------------------------------------------
            |Managers Payment 
            |--------------------------------------------------------------------------
         */
        Route::resource('managerpayments', 'ManagerPaymentsController');
        
        /*
            |--------------------------------------------------------------------------
            | Outstanding 
            |--------------------------------------------------------------------------
         */
            
        Route::resource('outstandings', 'OutstandingController');
        Route::post('/outstandings/commission/store', ['as'=>'outstandings.store_commissions', 'uses'=>'OutstandingController@store_commissions']);
        Route::match(['put', 'patch'], '/commission/store/{id}','OutstandingController@update_commissions');
        Route::get('/outstandings/{id}/agent/modify/{type}', ['as'=>'outstandings.modify', 'uses'=>'OutstandingController@status']);  
        Route::get('/outstandings/{id}/agent/paid/{type}', ['as'=>'outstandings.paid', 'uses'=>'OutstandingController@paid']);    
    });
            Route::get('/outstandings/agent/{id}/transactions/{status}', ['as'=>'outstandings.transactions', 'uses'=>'OutstandingController@transactions']);
            Route::get('/outstandings/agent/{id}/commission/{status}', ['as'=>'outstandings.commissions', 'uses'=>'OutstandingController@commissions']);

        /* Admin Middleware ends here
            |--------------------------------------------------------------------------
            | Members/Users 
            |--------------------------------------------------------------------------
         */
        Route::resource('members', 'UsersController');
        Route::get('/member/agent', ['as'=>'members.agent', 'uses'=>'UsersController@agent']);
        Route::get('/member/customer',['as'=>'members.customer','uses'=>'UsersController@customer']);
        Route::get('/member/search/{id}',['as'=>'members.search','uses'=>'UsersController@search']);
        Route::get('/member/password/edit/{id}',['as'=>'members.password','uses'=>'UsersController@password_edit']);
        Route::match(['put', 'patch'], '/password/modify/{id}','UsersController@passwordUpdate');
        Route::get('/member/{id}/status', ['as'=>'member.status', 'uses'=>'UsersController@status']);
        Route::match(['put', 'patch'], '/member/updatestatus/{id}','UsersController@updatestatus');
        
        /*
            |--------------------------------------------------------------------------
            | Home index 
            |--------------------------------------------------------------------------
         */
        
  
        /*
            |--------------------------------------------------------------------------
            | Agent 
            |--------------------------------------------------------------------------
         */

        Route::group(['middleware' =>['adminWithAgent']], function(){
        			Route::prefix('agent/')->group(function () {
        		    	Route::resource('senders', 'AgentCustomerController');
                        Route::get('/customers/{id}/list', ['as'=>'customer.list', 'uses'=>'AgentCustomerController@index']);
                        Route::get('/senders/autocomplete/{id}/{value}', ['as'=>'senders.autocomplete', 'uses'=>'AgentCustomerController@autocomplete']);
        		    	Route::resource('customer-transactions', 'AgentTransactionsController');
        		});

        });


        
       


        /*
            |--------------------------------------------------------------------------
            | Customer 
            |--------------------------------------------------------------------------
         */

main/resources/views/includes/form_error.blade.php
@if(count($errors) > 0 )

	<div class="row">
		    <div class=" col-md-4 col-md-offset-5  text-center error">

		        <ul>

		            @foreach($errors->all() as $error)


		                <li class="alert alert-danger">{{$error}}</li>


		            @endforeach



		        </ul>



		    </div>

	</div>


@endif

main/resources/views/includes/message.blade.php
@if(Session::has('message'))


	<div class="row">
		    <div class=" col-md-4 col-md-offset-5  text-center error">
		        <ul>
		                <li class="alert alert-success">{{Session::get('message')}}</li>

		        </ul>

		    </div>

	</div>


@endif


@if(Session::has('error'))


	<div class="row">
		    <div class=" col-md-4 col-md-offset-5  text-center error">
		        <ul>
		                <li class="alert alert-danger">{{Session::get('error')}}</li>

		        </ul>

		    </div>

	</div>


@endif

main/resources/views/includes/nav_header.blade.php
<nav class="navbar navbar-expand-lg navbar-light bg-primary">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<div id="logo_head">
						<img  src="{{asset('images/logo.png')}}" width="40px" height="40px> 
						<a class="navbar-brand" href="#"><strong> {{config('app.name')}}</strong></a>
					</div>
				</div>

				<div class="collapse navbar-collapse" >
					<ul class="nav navbar-nav" style = "color:#ffffff">
						<li><a  href={{route('members.home')}}><i class="fa fa-home fa-2x"></i></a></li>
						<li class="nav-item dropdown">
							@if(Auth::user()->isAgent())
								<a href="#" class=" dropdown-toggle" data-toggle="dropdown">Senders</a>
									<ul class="dropdown-menu">
										<li ><a href="{{route('senders.index')}}" class="dropdown-item">Senders List</a></li>
										<li><a href="{{route('senders.create')}}" class="dropdown-item">New Senders</a></li>
										<li ><a href="{{route('receivers.create')}}">New Receiver</a></li>
									</ul>
								@endif
							
							@if(Auth::user()->isCustomer())
								<a href="#"  dropdown-toggle" data-toggle="dropdown">Receivers</a>
									<ul class="dropdown-menu">
										<li ><a href="
										{{route('receivers.create')}}"
										 class="dropdown-item">New Receiver</a></li>
										<li><a href="
										{{route('receivers.sender',@Auth::id())}}"
											class="dropdown-item">View Receiver</a></li>
									</ul>
									
							@endif
						</li>
						@if(Auth::user()->isCustomer() || Auth::user()->isAgent())
							<li ><a href="{{route('transactions.create')}}">Send Money</a></li>
						@endif
						<li class="dropdown">
							<a href="#" class="dropdown-toggle"  data-toggle="dropdown">Transactions </a>
									
							<ul class="dropdown-menu">
									<li><a href={{route('transactions.index')}}>Previous Transaction</a></li>
									@if(Auth::user()->isAgent())
									<li><a href="{{route('outstandings.commissions',[Auth::id(),'all'])}}"> Commissions</a></li>
									<li><a href="{{route('outstandings.transactions',[Auth::id(),'all'])}}"> Outstanding</a></li>
									@endif
									
									<li><a href={{route('transactions.turnover',Auth::id())}}>Turnover</a></li>
									
							</ul>
						</li>
							@if(Auth::user()->isAdmin())
							<li class="dropdown">
								<a href="#" class="dropdown-toggle"  data-toggle="dropdown">Nigeria To UK </a>
								<ul class="dropdown-menu" >

									<li> <a href="{{route('transactions_n2uk.index')}}" > Transaction</a></li>

									<li><a href="{{route('transactions_n2uk.transfer',['0','0'])}}"> New Transfer</a></li>

									<li><a href="{{route('customers_n2uk.index')}}" > Customer</a></li>

									<li><a href={{route('customers_n2uk.create')}} > New Customer</a></li>

									<li><a href="{{route('rates_n2uk.index')}}" > Bou / Sold Rate</a></li>

									<li><a href="{{route('banks_n2uk.index')}}" > Receiver Bank</a></li>

							<!-- <li> <a href="{{route('managerpayments.index')}}" > Search</a></li>

							<li> <a href="{{route('managerpayments.index')}}" > TurnOver</a></li> -->
									
								</ul>
							</li>
						@endif				 				 
		         
				</ul>
				<small  style = "text-transform:capitalize; margin-top:14px;"> 
							Welcome {{str_limit(auth::user()->name,10)}}!</small>
					<ul class="nav navbar-nav navbar-right">
			@if(Auth::user()->type==='admin')
							<li class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown">General</a>
								<ul class="dropdown-menu">
									<li><a href={{route('currencies.index')}}>Currency Setup</a></li>
									<li><a href={{route('outstandings.index')}}>Outstandings</a></li>
									<li><a href={{route('payments.index')}}> Payments</a></li>
									<li><a href={{route('rate.index')}}>Rate Setup</a></li>
									<li><a href={{route('commission.index')}}>Commission Setup</a></li>
									<li><a href={{route('bank.index')}}>Bank Setup</a></li>
									<li><a href={{route('setup-business.index')}}>Businss Setting</a></li>
									<li><a href={{route('setup-transaction.index')}}>Transaction Setting</a></li>
									<li><a href={{route('subscription.index')}}>My Subscription</a></li>
									<li><a href="{{route('transactions.turnover',Auth::id())}}">Turnover</a></li>
								</ul>
							</li>
					@endif	
							<li class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown">My Account</a>
								<ul class="dropdown-menu">
									<li><a href={{route('members.password',@Auth::id())}}>Modify Password</a></li>
									<li><a href={{route('members.edit',@Auth::id())}}>Modify Profile</a></li>
								</ul>
							</li>
						
						<li><a href={{ url('/logout') }}><i class="fa fa-lock fa-2x"></i></a></li>
					</ul>
		</div>

	</nav>

main/resources/views/includes/sidebar.blade.php
	{!! Form::hidden('myurl',URL::to('/'),['id'=>'myurl']) !!}
	     <div class = "sidebar"> 
		  	<div class="panel panel-primary">
				<div class="panel-heading">
					<p class="text-center text-uppercase "><strong>		Account:{{auth::user()->type }}</strong></p>
				</div>
	        </div>
	        <div class="panel-body">
	        	
				<div id="user">
					<p class="text-Capitalize text-center"> <strong >Todays Rate!</strong></p>
				</div>
				<div class="panel-border">
					<div id="quickinfo" class="well well-lg text-danger">
					@foreach(App\Currency::rates() as $rate)
					<div class="row blink_me">
						<strong class="col-md-2 col-md-offset-1">£1 </strong>
						<strong class="col-md-1">= </strong>
						<strong class="col-md-7">{{$rate->rate}} {{$rate->destination_symbol}} </strong>
					</div><br>
					@endforeach
								
					</div>
				</div>
			      <div class="list-group">
					<a href={{route('members.home')}} class="list-group-item active"  >
						<span style="color:white;"><i class="glyphicon glyphicon-home"></i> Home</span>
					</a>
					@if(Auth::user()->isAdmin())
						 <a href="{{route('members.index')}}" class="list-group-item"><i class="fa fa-users"></i> Members</a>
					@endif
					<a href="{{route('transactions.index')}}" class="list-group-item"><i class="fa fa-briefcase"></i> Transactions</a>

					 @if(Auth::user()->isAgent() || Auth::user()->isCustomer() )
						<a href="{{route('transactions.create')}}" class="list-group-item"><i class="glyphicon glyphicon-send"></i> Send Money </a>
					@endif
					 @if(Auth::user()->isAgent())
						<a href="{{route('senders.create')}}" class="list-group-item"><i class="glyphicon glyphicon-plus"></i> New Sender</a>
												
						<a href="{{route('receivers.create')}}" class="list-group-item"><i class="glyphicon glyphicon-tags"></i> New Receivers</a>

						<a href="{{route('senders.index')}}" class="list-group-item"><i class="glyphicon glyphicon-user"></i> Senders List</a>
						<a href="{{route('outstandings.commissions',[Auth::id(),'all'])}}" class="list-group-item"><i class="glyphicon glyphicon-user"></i> Commissions</a>
						<a href="{{route('outstandings.transactions',[Auth::id(),'all'])}}" class="list-group-item"><i class="glyphicon glyphicon-user"></i> Outstanding</a>
						
												
						
					@endif

					@if(Auth::user()->type == 'customer')
					 <a href="{{route('receivers.create')}}" class="list-group-item"><i class="glyphicon glyphicon-plus"></i> New Receiver</a>
									 	 
					 <a href="{{route('receivers.index')}}" class="list-group-item"><i class="glyphicon glyphicon-user"></i> Receivers</a>
									
					@endif
					
					@if(Auth::user()->isManager() || Auth::user()->isAdmin())	
						<a href="{{route('outstandings.index')}}" class="list-group-item"><i class="fa fa-briefcase"></i> Outstandings Balance</a>
					@endif		
					@if(Auth::user()->isAdmin())
						<a href="{{route('rate.index')}}" class="list-group-item"><i class="fa fa-unlock-alt"></i> Modify Rate</a>
						<a href="{{route('commission.index')}}" class="list-group-item"><i class="fa fa-money"></i> Modify Commission</a>
						<a href="{{route('bank.index')}}" class="list-group-item"><i class="fa fa-institution"></i> Banks</a>
						<a href="{{route('setup-business.index')}}" class="list-group-item"> Business Setting</a>
						<a href="{{route('setup-transaction.index')}}" class="list-group-item"> Transaction Setting</a>
						<a href="{{route('payments.index')}}" class="list-group-item"> Payments</a>
						<a href="{{route('transactions.turnover',Auth::id())}}" class="list-group-item"><i class="fa fa-briefcase"></i> Turnover</a>
					<!-- <a href="{{route('managerpayments.index')}}" class="list-group-item"><i class="fa fa-briefcase"></i> Managers Payments</a> -->
<!--N2UK-------------- -->
						<div class="dropdown">
							<button class="btn-primary btn-block"
										  id="dLabel" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
										     Nigeria to UK Transfer
										    <span class="caret"></span>
							</button>
							<ul class="dropdown-menu" aria-labelledby="dLabel">

								 <a href="{{route('transactions_n2uk.index')}}" class="list-group-item"><i class="fa fa-institution"></i> Transaction</a>

								<a href="{{route('transactions_n2uk.transfer',['0','0'])}}" class="list-group-item"><i class="fa fa-institution"></i> New Transfer</a>

								<a href="{{route('customers_n2uk.index')}}" class="list-group-item"><i class="fa fa-institution"></i>  Customer</a>

								<a href={{route('customers_n2uk.create')}} class="list-group-item"><i class="fa fa-institution"></i> New Customer</a>

								<a href="{{route('rates_n2uk.index')}}" class="list-group-item"><i class="fa fa-institution"></i> Bou / Sold Rate</a>

								<a href="{{route('banks_n2uk.index')}}" class="list-group-item"><i class="fa fa-institution"></i> Receiver Bank</a>

								<!-- <a href="{{route('managerpayments.index')}}" class="list-group-item"><i class="fa fa-institution"></i> Search</a>

								 <a href="{{route('managerpayments.index')}}" class="list-group-item"><i class="fa fa-institution"></i> TurnOver</a> -->
								
							</ul>
						</div>
						@endif				 				 
		         </div>
		      </div>
	</div>

main/resources/views/includes/type_navigation.blade.php
<ol class="breadcrumb">
					<div class="linkhead">
						<div class="row">
							<div class="col-md-10 col-md-offset-2">
								<div class="row">
									<div class="col-sm-5 ">
										<a href="transactions/agent" class="btn bt-primary bg">
											Agent
										</a>
									</div>
									<div class="col-sm-5 col-sm-1">
										<a href="#" class="btn bt-primary bg">Customer</a>
									</div>
								</div>
							</div>
						</div>
					</div>
</ol>