main/routes/web.php
<?php
use Illuminate\Http\Request;
use App\User;
use App\AgentCustomer;
use App\Receiver;
use App\Transaction;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/  
 

Route::get('/payment/{type}/{id}/', ['as'=>'payments.pay', 'uses'=>'PaymentsController@pay']);
Route::get('/payment/part/user/{id}/{amount}', ['as'=>'payments.part_pay', 'uses'=>'PaymentsController@part_pay']);
Route::post('/paypal/payments', ['as'=>'payments.paypal', 'uses'=>'PaymentsController@paypal_store']);
Route::post('/paypal/strip', ['as'=>'payments.strip', 'uses'=>'PaymentsController@stripe_store']);
Route::get('status', 'PayPalController@getPaymentStatus');


Route::group(['middleware' =>'isLogin'], function(){

    Route::get('/message/{type}/{id}/validate_mobile', ['as'=>'message.validate_mobile', 'uses'=>'MessageController@validate_mobile']);
    
    Route::post('/mobile/confirm_code',  'MessageController@confirm_code');
 
     Route::get('/',['as'=>'members.home','uses'=>'UsersController@home']);
     
     Route::get('/home',['as'=>'members.home','uses'=>'UsersController@home']);

     Route::get('/currency/sender/{id}',['as'=>'currencies.sender','uses'=>'CurrenciesController@sender']);
       
 /*
    |--------------------------------------------------------------------------
    | Admin
    |--------------------------------------------------------------------------
     
            */
         Route::group(['middleware' =>'admin'], function(){
             /*
              |--------------------------------------------------------------------------
              | Payments 
              |--------------------------------------------------------------------------
          */
            Route::resource('payments', 'PaymentsController');
            Route::get('/{type}/user/payment', ['as'=>'payments.user_type', 'uses'=>'PaymentsController@user_type']);
            Route::post('/post_search/payment', ['as'=>'payments.post_search', 'uses'=>'PaymentsController@post_search']);
            /*
              |--------------------------------------------------------------------------
              | Subscription 
              |--------------------------------------------------------------------------
          */
          Route::resource('subscription', 'SubscriptionController');

                Route::resource('admin', 'AdminController');
                  /*
                    |--------------------------------------------------------------------------
                    | Subscription 
                    |--------------------------------------------------------------------------
                */
                Route::resource('subscription', 'SubscriptionController');

                /*
                    |--------------------------------------------------------------------------
                    | Rate 
                    |--------------------------------------------------------------------------
                */
                Route::resource('rate', 'RateController');

                   /*
                    |--------------------------------------------------------------------------
                    | Currencies 
                    |--------------------------------------------------------------------------
                */
                Route::resource('currencies', 'CurrenciesController');
                
                /*
                    |--------------------------------------------------------------------------
                    | Commission 
                    |--------------------------------------------------------------------------
                */
                Route::resource('commission', 'CommissionController');
                /*
                    |--------------------------------------------------------------------------
                    | Bank 
                    |--------------------------------------------------------------------------
                */
                Route::resource('bank', 'BankController');
                /*
                    |--------------------------------------------------------------------------
                    | Business Setup
                    |--------------------------------------------------------------------------
                */

                Route::resource('setup-business', 'SetupBusinessController');
                /*
                    |--------------------------------------------------------------------------
                    | Transaction Setup
                    |--------------------------------------------------------------------------
                */

                Route::resource('setup-transaction', 'SetupTransactionController');

        /*
                    |--------------------------------------------------------------------------
                    | Message
                    |--------------------------------------------------------------------------
         */

        Route::resource('message', 'MessageController');
        Route::get('/user/{id}/message', ['as'=>'message.user', 'uses'=>'MessageController@index']);

                
        /*
            |--------------------------------------------------------------------------
            | Payment 
            |--------------------------------------------------------------------------
         */
            
        Route::resource('partpayment', 'PartPaymentController');
        Route::get('/partpayment/{id}/agent/transactions', ['as'=>'partpayment.transactions', 'uses'=>'PartPaymentController@transactions']);
        Route::get('/partpayment/{id}/agent/commission', ['as'=>'partpayment.commissions', 'uses'=>'PartPaymentController@commissions']);
        Route::post('/post_search/partpayment', ['as'=>'partpayment.post_search', 'uses'=>'PartPaymentController@post_search']);
       
        
        /*
            |--------------------------------------------------------------------------
            |Managers Payment 
            |--------------------------------------------------------------------------
         */
        Route::resource('managerpayments', 'ManagerPaymentsController');
        
        /*
            |--------------------------------------------------------------------------
            | Outstanding 
            |--------------------------------------------------------------------------
         */
            
        Route::resource('outstandings', 'OutstandingController');
        Route::post('/outstandings/commission/store', ['as'=>'outstandings.store_commissions', 'uses'=>'OutstandingController@store_commissions']);
        Route::match(['put', 'patch'], '/commission/store/{id}','OutstandingController@update_commissions');
        Route::get('/outstandings/{id}/agent/modify/{type}', ['as'=>'outstandings.modify', 'uses'=>'OutstandingController@status']);  
        Route::get('/outstandings/{id}/agent/paid/{type}', ['as'=>'outstandings.paid', 'uses'=>'OutstandingController@paid']);    
    });
            Route::get('/outstandings/agent/{id}/transactions/{status}', ['as'=>'outstandings.transactions', 'uses'=>'OutstandingController@transactions']);
            Route::get('/outstandings/agent/{id}/commission/{status}', ['as'=>'outstandings.commissions', 'uses'=>'OutstandingController@commissions']);

        /* Admin Middleware ends here
            |--------------------------------------------------------------------------
            | Members/Users 
            |--------------------------------------------------------------------------
         */
        Route::resource('members', 'UsersController');
        Route::get('/member/agent', ['as'=>'members.agent', 'uses'=>'UsersController@agent']);
        Route::get('/member/customer',['as'=>'members.customer','uses'=>'UsersController@customer']);
        Route::get('/member/search/{id}',['as'=>'members.search','uses'=>'UsersController@search']);
        Route::get('/member/password/edit/{id}',['as'=>'members.password','uses'=>'UsersController@password_edit']);
        Route::match(['put', 'patch'], '/password/modify/{id}','UsersController@passwordUpdate');
        Route::get('/member/{id}/status', ['as'=>'member.status', 'uses'=>'UsersController@status']);
        Route::match(['put', 'patch'], '/member/updatestatus/{id}','UsersController@updatestatus');
        
        /*
            |--------------------------------------------------------------------------
            | Home index 
            |--------------------------------------------------------------------------
         */
        
  
        /*
            |--------------------------------------------------------------------------
            | Agent 
            |--------------------------------------------------------------------------
         */

        Route::group(['middleware' =>['adminWithAgent']], function(){
        			Route::prefix('agent/')->group(function () {
        		    	Route::resource('senders', 'AgentCustomerController');
                        Route::get('/customers/{id}/list', ['as'=>'customer.list', 'uses'=>'AgentCustomerController@index']);
                        Route::get('/senders/autocomplete/{id}/{value}', ['as'=>'senders.autocomplete', 'uses'=>'AgentCustomerController@autocomplete']);
        		    	Route::resource('customer-transactions', 'AgentTransactionsController');
        		});

        });


        
       


        /*
            |--------------------------------------------------------------------------
            | Customer 
            |--------------------------------------------------------------------------
         */

main/resources/views/admin/2delete/transactions.blade.php
@extends('layouts.layout')
@section('content')
	<div class="row">
						<div class="col-md-6 col-md-offset-4">
							<div class="ui-widget">
									<input type="text" id="getTransactions" class="form-control" placeholder=" Search WE£446GF,0796643,John " >
									</div>
						</div>
						<div class="col-md-2">
									<a href="#" id ="clicksearch">Search by Date</a>
									<a href="{{route('transactions.search',
									['type' =>'today','value'=>'today'])}}">Today</a>&nbsp;
									<a href="{{route('transactions.search',
									['type' =>'yesterday','value'=>'yesterday'])}}">Yesterday</a>
									<a href="{{route('transactions.search',
									['type' =>'month','value'=>'month'])}}">Month ago</a>
						</div>

	</div>
	<div class= "row"  id = "datesearch">
				<div class="col-md-5 col-md-offset-2">
								{!! Form::label('From', 'From Date')!!}
					<div class="form-group input-group form-group-sm">
					 <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
						{!! Form::date('from', '09/04/2015', ['class'=>'form-control','id'=>'datefrom'])!!}
					</div>
				</div>

				<div class="col-md-5">
								{!! Form::label('To', 'To Date')!!}
					<div class="form-group input-group form-group-sm">
					 <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
						{!! Form::date('to', '09/04/2015', ['class'=>'form-control','id'=>'dateto'])!!}
					</div>
				</div>
	</div>
	<br/>
	 <div class="row">
					<div class="col-md-3">
						<ol class="breadcrumb">
						<li class="active">{{$header==$header?$header:""}} Transactions</li>
						</ol>
					</div>
	@if(Auth::user()->type == 'admin')			
					<div class="col-md-4 col-md-offset-2">
						<ol class="breadcrumb">
							<li class="active"><a href="{{route('transactions.customer')}}">Customer</a></li>
							<li class="active"><a href="{{route('transactions.agent')}}">Agent</a></li>
						</ol>
					</div>			
	</div>
	@endif
	<div class="row">
		<div class="col-md-12">
			 <table id="sort-table" class="table table-striped table-bordered tablesorter">
				<thead>
							<tr>
								<th>No </th>
								<th>Date <i class=""></i></th>
								<th>Tcode  </th>
								<th>Sender <i class=""></i></th>
								<th>Receiver </th>
								<th>Amt</th>
								<th>Local Pay</th>
								<th>C_B</th>
								<th>C-ag</th>
								<th>Total</th>
								<th>Status</th>
								<th>--</th>
								<th>--</th>
								<th>--</th>
							</tr>
					</thead>
					<tbody>
						<?php $x=0;$tamt_send=0;$totalAmount=0;$totalLocalAmount=0;$totalAgentCommission=0;$totalBusinessCommission=0; $tTotal=0; ?>
			@foreach($transactions as $transaction)
							<tr>
							<td>{{$x=$x+1}}</td>
							<td>{{ $transaction->created_at->diffForhumans()}}</td>
							<td>{{ucfirst($transaction->receipt_number)}}</td>
							<td>{{ $transaction->sender_name}}</td>
							<td>{{ $transaction->receiver_name}}</td>
							<td>{{ number_format($transaction->amount, 2)}}</td>
							<td>{{$transaction->local_payment}}</td>
							<td>{{$transaction->business_commission}}</td>
							<td>{{$transaction->agent_commission}}</td>
							<td>{{$transaction->total}}</td>
							<td> <a href="{{route('transactions.status',
								$transaction->id)}}"class="btn btn-success">{{$transaction->status}}</a></td>
<!---Sum Here-->
							<?php
							$totalAmount += $transaction->amount;
							$totalLocalAmount += ($transaction->amount * $transaction->exchange_rate);
							$totalAgentCommission += ($transaction->commission * ($transaction->agent_commission/100));
							$totalBusinessCommission += ($transaction->commission * (100-$transaction->agent_commssion)/100);
							$tTotal +=($transaction->amount + $transaction->commission);		
							?>
									
									
							<td> <a href="{{route('transactions.edit',$transaction->id)}}" class="btn btn-warning">Edit</a></td>

							{!! Form::open(['method'=>'DELETE', 'action'=>[ 'AgentTransactionsController@destroy',$transaction->id], 'files'=>true]) !!}
								<td>{!! Form::submit('Delete',['class'=>'btn btn-danger']) !!}</td>
							{!! Form::close() !!}
								
							<td><a href="{{route('transactions.receipt',$transaction->id)}}" class="btn btn-info"><i class="fa fa-print" aria-hidden="true"></i>Receipt</a></td>		
									
								 </tr>
							 @endforeach

							 <tr>
								<td colspan="5"><strong>Total</td>
								<td><strong>&pound;{{number_format(($transactions->sum('amount')),2)}}</strong></td>
								<td><strong>&#8358;{{number_format($totalLocalAmount,2)}}</strong></td>
								<td><strong>&pound;{{ number_format($totalAgentCommission,2)}}</strong></td>
								<td><strong>&pound;{{ number_format($totalBusinessCommission,2)}}</strong></td>
								<td><strong>&pound;{{ number_format($tTotal,2) }}</strong></td>
								</strong>
							</tr>
						</tbody>
			</table>
				<div class="row">
					<div class="col-md-5 col-md-offset-3 text-center">
						{{$transactions->render()}}
					</div>
				</div>
		</div>
	</div>
@endsection

@section('script')
	$(function(){
<!--Trigger Autocomplete --> 
				 $('#clicksearch').on('click', function(e) {
				      $('#datesearch').toggle();
				      e.preventDefault();
				    });
				 url  = $('#myurl').val() + '/transaction/search'  
<!--Autocomplete --> 
				 $( "#getTransactions" ).autocomplete({	
				 	max:10,
					//source:'quickSearch.php',
					
						 source: function (request, response) {
							 $.ajax({
								 url:  "{{route('transactions.autocompletetips',"")}}"+"/" + request.term ,
								 data: { term: request.term },
								 dataType: "json",
								 success: response,
								 error: function () {
									 response([]);
								 }
							 });
						 },
					select: function( event, ui ) {
						var add=url;		
					window.location.href = add+'/id/'+ui.item.id;
					}
    });
   <!--Date Search --> 
   					$('#dateto').on('change', function (e) {
   					value = $('#datefrom').val() + ',' + $('#dateto').val()
   					window.location.href = url +'/date/'+ value
   				});
				
			});
@endsection