main/routes/web.php
<?php
use Illuminate\Http\Request;
use App\User;
use App\AgentCustomer;
use App\Receiver;
use App\Transaction;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/  
 

Route::get('/payment/{type}/{id}/', ['as'=>'payments.pay', 'uses'=>'PaymentsController@pay']);
Route::get('/payment/part/user/{id}/{amount}', ['as'=>'payments.part_pay', 'uses'=>'PaymentsController@part_pay']);
Route::post('/paypal/payments', ['as'=>'payments.paypal', 'uses'=>'PaymentsController@paypal_store']);
Route::post('/paypal/strip', ['as'=>'payments.strip', 'uses'=>'PaymentsController@stripe_store']);
Route::get('status', 'PayPalController@getPaymentStatus');


Route::group(['middleware' =>'isLogin'], function(){

    Route::get('/message/{type}/{id}/validate_mobile', ['as'=>'message.validate_mobile', 'uses'=>'MessageController@validate_mobile']);
    
    Route::post('/mobile/confirm_code',  'MessageController@confirm_code');
 
     Route::get('/',['as'=>'members.home','uses'=>'UsersController@home']);
     
     Route::get('/home',['as'=>'members.home','uses'=>'UsersController@home']);

     Route::get('/currency/sender/{id}',['as'=>'currencies.sender','uses'=>'CurrenciesController@sender']);
       
 /*
    |--------------------------------------------------------------------------
    | Admin
    |--------------------------------------------------------------------------
     
            */
         Route::group(['middleware' =>'admin'], function(){
             /*
              |--------------------------------------------------------------------------
              | Payments 
              |--------------------------------------------------------------------------
          */
            Route::resource('payments', 'PaymentsController');
            Route::get('/{type}/user/payment', ['as'=>'payments.user_type', 'uses'=>'PaymentsController@user_type']);
            Route::post('/post_search/payment', ['as'=>'payments.post_search', 'uses'=>'PaymentsController@post_search']);
            /*
              |--------------------------------------------------------------------------
              | Subscription 
              |--------------------------------------------------------------------------
          */
          Route::resource('subscription', 'SubscriptionController');

                Route::resource('admin', 'AdminController');
                  /*
                    |--------------------------------------------------------------------------
                    | Subscription 
                    |--------------------------------------------------------------------------
                */
                Route::resource('subscription', 'SubscriptionController');

                /*
                    |--------------------------------------------------------------------------
                    | Rate 
                    |--------------------------------------------------------------------------
                */
                Route::resource('rate', 'RateController');

                   /*
                    |--------------------------------------------------------------------------
                    | Currencies 
                    |--------------------------------------------------------------------------
                */
                Route::resource('currencies', 'CurrenciesController');
                
                /*
                    |--------------------------------------------------------------------------
                    | Commission 
                    |--------------------------------------------------------------------------
                */
                Route::resource('commission', 'CommissionController');
                /*
                    |--------------------------------------------------------------------------
                    | Bank 
                    |--------------------------------------------------------------------------
                */
                Route::resource('bank', 'BankController');
                /*
                    |--------------------------------------------------------------------------
                    | Business Setup
                    |--------------------------------------------------------------------------
                */

                Route::resource('setup-business', 'SetupBusinessController');
                /*
                    |--------------------------------------------------------------------------
                    | Transaction Setup
                    |--------------------------------------------------------------------------
                */

                Route::resource('setup-transaction', 'SetupTransactionController');

        /*
                    |--------------------------------------------------------------------------
                    | Message
                    |--------------------------------------------------------------------------
         */

        Route::resource('message', 'MessageController');
        Route::get('/user/{id}/message', ['as'=>'message.user', 'uses'=>'MessageController@index']);

                
        /*
            |--------------------------------------------------------------------------
            | Payment 
            |--------------------------------------------------------------------------
         */
            
        Route::resource('partpayment', 'PartPaymentController');
        Route::get('/partpayment/{id}/agent/transactions', ['as'=>'partpayment.transactions', 'uses'=>'PartPaymentController@transactions']);
        Route::get('/partpayment/{id}/agent/commission', ['as'=>'partpayment.commissions', 'uses'=>'PartPaymentController@commissions']);
        Route::post('/post_search/partpayment', ['as'=>'partpayment.post_search', 'uses'=>'PartPaymentController@post_search']);
       
        
        /*
            |--------------------------------------------------------------------------
            |Managers Payment 
            |--------------------------------------------------------------------------
         */
        Route::resource('managerpayments', 'ManagerPaymentsController');
        
        /*
            |--------------------------------------------------------------------------
            | Outstanding 
            |--------------------------------------------------------------------------
         */
            
        Route::resource('outstandings', 'OutstandingController');
        Route::post('/outstandings/commission/store', ['as'=>'outstandings.store_commissions', 'uses'=>'OutstandingController@store_commissions']);
        Route::match(['put', 'patch'], '/commission/store/{id}','OutstandingController@update_commissions');
        Route::get('/outstandings/{id}/agent/modify/{type}', ['as'=>'outstandings.modify', 'uses'=>'OutstandingController@status']);  
        Route::get('/outstandings/{id}/agent/paid/{type}', ['as'=>'outstandings.paid', 'uses'=>'OutstandingController@paid']);    
    });
            Route::get('/outstandings/agent/{id}/transactions/{status}', ['as'=>'outstandings.transactions', 'uses'=>'OutstandingController@transactions']);
            Route::get('/outstandings/agent/{id}/commission/{status}', ['as'=>'outstandings.commissions', 'uses'=>'OutstandingController@commissions']);

        /* Admin Middleware ends here
            |--------------------------------------------------------------------------
            | Members/Users 
            |--------------------------------------------------------------------------
         */
        Route::resource('members', 'UsersController');
        Route::get('/member/agent', ['as'=>'members.agent', 'uses'=>'UsersController@agent']);
        Route::get('/member/customer',['as'=>'members.customer','uses'=>'UsersController@customer']);
        Route::get('/member/search/{id}',['as'=>'members.search','uses'=>'UsersController@search']);
        Route::get('/member/password/edit/{id}',['as'=>'members.password','uses'=>'UsersController@password_edit']);
        Route::match(['put', 'patch'], '/password/modify/{id}','UsersController@passwordUpdate');
        Route::get('/member/{id}/status', ['as'=>'member.status', 'uses'=>'UsersController@status']);
        Route::match(['put', 'patch'], '/member/updatestatus/{id}','UsersController@updatestatus');
        
        /*
            |--------------------------------------------------------------------------
            | Home index 
            |--------------------------------------------------------------------------
         */
        
  
        /*
            |--------------------------------------------------------------------------
            | Agent 
            |--------------------------------------------------------------------------
         */

        Route::group(['middleware' =>['adminWithAgent']], function(){
        			Route::prefix('agent/')->group(function () {
        		    	Route::resource('senders', 'AgentCustomerController');
                        Route::get('/customers/{id}/list', ['as'=>'customer.list', 'uses'=>'AgentCustomerController@index']);
                        Route::get('/senders/autocomplete/{id}/{value}', ['as'=>'senders.autocomplete', 'uses'=>'AgentCustomerController@autocomplete']);
        		    	Route::resource('customer-transactions', 'AgentTransactionsController');
        		});

        });


        
       


        /*
            |--------------------------------------------------------------------------
            | Customer 
            |--------------------------------------------------------------------------
         */

main/app/Http/Controllers/Api/2beDeleted/CustomersController.php
<?php

namespace App\Http\Controllers\Api;
use App\AgentCustomer;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CustomersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index($id)
    {
        //
       
        return response()->json(
                            AgentCustomer::whereUser_id($id)
                            ->select('name','mobile','id') ->get());                         
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $input = $request->all();
        $customer = AgentCustomer::create($input);
         response()->json($customer);


    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

main/app/Http/Controllers/Api/AgentsController.php
<?php

namespace App\Http\Controllers\Api;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AgentsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

main/app/Http/Controllers/N2UK/CustomersController.php
<?php

namespace App\Http\Controllers\N2UK;
use App\N2UK\Customer;
use Auth;
use Illuminate\Http\Request;
use App\Http\Requests\n2uk\CustomerRequest;
use App\Http\Controllers\Controller;
use DB;

class CustomersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
         $customers = Customer::paginate('10');
        return view('n2uk.customers.index',compact('customers'));
    }

    //autocomplete for search
    public function autocomplete($id = null )
    {
        return                     
        response()->json(Customer::select(DB::raw("CONCAT(fname,'-',lname) AS value"),'id')
                        ->get());
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('n2uk.customers.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
     private function checkemptyadress($input){
            $input['postcode'] = $input['postcode'] ==""?"none": $input['postcode'];
            $input['number'] = $input['number'] ==""?"": $input['number'];
            $input['address'] = $input['address'] ==""?$input['search']: $input['address'];
            $input['town'] =   $input['town'] ==""?"": $input['town'];
            $input['county'] = $input['county'] ==""?"": $input['county'];
            $input['country'] = $input['country'] ==""?"": $input['country'];
            $input['address'] =  $input['number']. " ".$input['address']. " ".$input['town']." ".$input['county']." ".$input['country'];
            return $input;

    }
    public function store(CustomerRequest $request)
    {
        //
        //check for empty inputs
            $input = $request->all();
            $input['name']= $input['fname']." ".$input['lname'];
            $input = $this->checkemptyadress($input);
             
           $input['user_id'] = Auth::id();

            Customer::create($input);
            \Session::flash('message','Your new Customer sucessfully created');
             return redirect('customers_n2uk');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $customers = Customer::whereId($id)->paginate('10');
        return view('n2uk.customers.index',compact('customers'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $customer = Customer::findorfail($id);
        return view('n2uk.customers.edit',compact('customer'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
            $input = $request->all();
            $input = $this->checkemptyadress($input);
            Customer::whereId($id)->first()->update($input);


           // $agentcustomer->update($input);
            \Session::flash('message','successfully updated');
             return redirect('customers_n2uk');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $customer = Customer::findorfail($id);
        $customer->delete();
        \Session::flash('message','Customer Successfully Deleted');
        return redirect('customers_n2uk');
    }
}

main/resources/views/agent/customers/create.blade.php
@extends('layouts.layout')
@section('content')

					<div class="row">
						<div class="col-md-4">
							<small class="essential">Fields Marked with [*] are mandatory</small>
						</div>
						<div class="col-md-4">	
							<ol class="breadcrumb">
							  <li><a href={{route('members.home')}}>Home</a></li>
							  <li><a href={{route('senders.index')}}>Senders</a></li>
							  <li class="active">New Senders</li>
							</ol>
						</div>
					</div><h4>Register New Sender</h4>
<!-- Form -->
		{!! Form::open(['method'=>'POST', 'action'=> 'AgentCustomerController@store', 'files'=>true]) !!}
		{!! Form::hidden('user_id',@Auth::id(),['id'=>'user_id']) !!}
		
		
					 <div class="panel panel-default">
						<div class="panel-heading">
							
						</div>
					<div class="panel-body">
						<div class="row">
								<div class="col-md-5 col-md-offset-1">
										<div class="form-group form-group-sm">
											{!! Form::label('title', 'Title:') !!}
							                {!! Form::select('title', ['mr'=>'Mr','miss'=>'Miss','mrs'=>'Mrs'] , null, ['class'=>'form-control'])!!}
										</div>
								</div>	

									
								<div class="col-md-5">
									<div class="form-group form-group-sm">
									{!! Form::label('Country Destination','Country Destination') !!}
									{!! Form::select('currency_id',$currencies,null,['class'=>'form-control','required'=>'required','id'=>'currency_id']) !!}
									</div>
								</div>
																					
						
						</div>
							<div class="row">																					
								<div class="col-md-5 col-md-offset-1 ">
									<div class="form-group form-group-sm">
										<span class="essential">*</span>
										{!! Form::label('fname', 'First Name')!!}
										{!! Form::text('fname', null, ['class'=>'form-control'])!!}
													
									</div>
								</div>
										
								<div class="col-md-5">
										<div class="form-group">
										
										{!! Form::label('mname', 'Middle Name')!!}
										{!! Form::text('mname', null, ['class'=>'form-control'])!!}
													
									</div>
								</div>
							</div>
							
							<div class="row">																				
								<div class="col-md-5 col-md-offset-1">
										<div class="form-group form-group-sm">
											<span class="essential">*</span>
											{!! Form::label('lname', 'Last Name')!!}
											{!! Form::text('lname', null, ['class'=>'form-control'])!!}
														
										</div>
								</div>
										
										<div class="col-md-5">
												{!! Form::label('dob', 'Date Of Birth')!!}
												<span class="essential">*</span>
												<div class="form-group input-group form-group-sm">
													 <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
													{!! Form::date('dob', '09/04/2015', ['class'=>'form-control'])!!}
												</div>
										</div>
							</div>
							<div class="row">
							
									<div class="title_header">Contact Information</div>
									
							</div>
							<div class="row">	
								<div class="col-md-5 col-md-offset-1">
									<div class="form-group form-group-sm">
										{!! Form::label('phone', 'Phone Number')!!}
										{!! Form::text('phone', null, ['class'=>'form-control'])!!}
														
									</div>
								</div>
										
								<div class="col-md-5">
									<div class="form-group form-group-sm">
										<span class="essential">*</span>
										{!! Form::label('mobile', 'Mobile Number')!!}
										{!! Form::text('mobile', null, ['class'=>'form-control'])!!}
														
									</div>
								</div>
							</div>
							
							<div class="row">													
								<div class="col-md-5 col-md-offset-1">
									<div class="form-group form-group-sm">
										{!! Form::label('email', 'Email')!!}
										{!! Form::text('email', null, ['class'=>'form-control'])!!}
														
									</div>
								</div>
								<div class="col-md-5">
									<div class="form-group form-group-sm">
										{!! Form::label('cemail', 'Confirm Email')!!}
										{!! Form::text('cemail', null, ['class'=>'form-control'])!!}
									</div>
								</div>
							</div>
							
							<div class="row">
											<div class="title_header">Address</div>
										<div class="col-md-7 col-md-offset-2">
											{!! Form::label('Address Postocode', 'Address / Postcode')!!}<span class="essential">*</span>
										</div>
										<div class="col-md-7 col-md-offset-2">
												<div class="form-group form-group-sm">
													<input name = "search" type=text required name=postcode id="autocomplete" class="form-control"  onFocus="geolocate()">
												</div>
												
   										 </div>
							</div>
											
								
							<br/><br/>
							<div class="row">
								<div class="col-md-2 col-md-offset-2">
									<div class="form-group form-group-sm">
										{!! Form::label('No', 'Number')!!}
										{!! Form::text('number', null, ['class'=>'form-control','id'=>'street_number', 'required'=>'required'])!!}
									</div>		
								</div>
								<div class="col-md-7">
									<div class="form-group form-group-sm">
										{!! Form::label('Address', 'Address')!!}
										{!! Form::text('address', null, ['class'=>'form-control','id'=>'route','readonly'=>'readonly'])!!}
									</div>		
								</div>
										
										
							</div>
							<div class="row">
										<div class="col-md-5 col-md-offset-1 ">
											<div class="form-group form-group-sm">
												{!! Form::label('postcode', 'Post Code')!!}
												{!! Form::text('postcode', null, ['class'=>'form-control','id'=>'postal_code','readonly'=>'readonly'])!!}
											</div>
										</div>
										
										<div class="col-md-5">
												<div class="form-group form-group-sm">
												{!! Form::label('town', 'Town')!!}
												{!! Form::text('town', null, ['class'=>'form-control','id'=>'locality','readonly'=>'readonly'])!!}
											</div>
										</div>
							</div>																		
							
							<div class="row">
										<div class="col-md-5 col-md-offset-1">
												<div class="form-group form-group-sm">
												{!! Form::label('county', 'County')!!}
												{!! Form::text('county', null, ['class'=>'form-control','id'=>'administrative_area_level_1','readonly'=>'readonly'])!!}
											</div>
										</div>
										
											<div class="col-md-5">
												<div class="form-group form-group-sm">
												{!! Form::label('country', 'Country')!!}
												{!! Form::text('country', null, ['class'=>'form-control','id'=>'country','readonly'=>'readonly'])!!}
											</div>
											</div>
							</div>
							
										<div class="row">
											<div class="col-md-5 col-md-offset-1">
												<div class="title_header"><span class="essential">*</span>Terms And Conditions</div>
											</div>
										</div>
										<div class="row">	
												<div class="col-md-12">
														<p><strong>Clicking the submit button you have read and accepted the <a href="terms.php">TERMS AND CONDITIONS</a> and Your information will be held securely 
														with our data protection and management policy?</strong><p>
												</div>																																
										
										</div>
									
										<div class="row">
												<div class="col-md-5 col-md-offset-3 ">
													{!! Form::submit('Submit', ['class'=>'btn btn-primary btn-block'])!!}					
												</div>			
										</div>	
					</div>
			{!! Form::close() !!}

@endsection

main/resources/views/agent/customers/index.blade.php
@extends('layouts.layout')
@section('content')


<div class="row">										
				<div class="col-md-8" >		
					<input  type="text" class="form-control" id="getsender" placeholder="Search...">
				</div>
					
					<div class="col-md-4">
						<span style="float:right;"><?php //echo $pages; ?>
								 <?php //echo $items; ?></span>
								
								<nav style="float:right;">
								 <ul class="pagination">
								<?php //echo $pagin;?>
								</ul>
								</nav>
					</div>
					
			</div>
					<h6>Senders</h6>
					@if(count($senders) > 0)
					   <table id="sort-table" class="table table-striped tablesorter">
						  <thead >
							<tr class="text-center">
									<th>No </th>
									<th>Sender <i class="caret"></i></th>
									
									<th>Mobile <i class="caret"></i></th>
									<th colspan = "4" class="text-center">Actions</th>
							</tr>
						<thead>
						<tbody>
					
					
					
					 <?php $x=0; foreach($senders as $sender): ?>
						<tr>
							<td><?php  echo $x=$x+1;?></td>
							<td><a href="{{route('senders.edit',$sender->id)}}">
								<?php  echo ucfirst($sender->title)." ".ucfirst($sender->fname)." ". ucfirst($sender->lname);?></a></a></td>
							
							<td><?php  echo $sender->mobile;?></td>
							<td><a href="{{route('receivers.new',$sender->id)}}" class="btn btn-default "><i class="fa fa-users "></i> New Receiver</a></td>	
						 	
						 	<td><a href="{{route('senders.edit',$sender->id)}}" class="btn btn-default"><i class="fa fa-users "></i> Modify</a></td>	
							
							<td>
							<a href="
								{{route('receivers.sender',$sender->id)}}" class="btn btn-default">
								<i class="fa fa-user fa-md"></i> Receivers [{{App\Receiver::whereSender_id($sender->id)->count()}}]
							</a></td>

							<td> 
											@if(Auth::user()->isAdmin())
												{!! Form::open(['method'=>'DELETE', 'action'=>[ 'AgentCustomerController@destroy',
													$sender->id], 'files'=>true,'class'=>'delete']) !!}
													{!! Form::submit('Delete',['class'=>'delete btn btn-danger']) !!}
											{!! Form::close() !!}
										
											@endif
							</td>
							
							<td>
							@if(Auth::user()->type === 'agent' || Auth::user()->type === 'customer')
								<a href="{{route('transaction.create',['sender_id'=>$sender->id,'receiver_id'=>'null']) }}" 
								class="btn btn-primary">
								<i class="fa fa-money fa-lg"></i>  Send Money</a>
								@endif
							</td>
					 </tr>
						  <?php endforeach; ?>
				
				 </tbody>
			</table>
			@else
					<p><strong class = "col-md-12 text-center text-danger"> No Sender Available</strong></p>
				@endif
						{{$senders->render()}}
@endsection


@section('script')

<!--confirm Delete --> 
				$(".delete").on("submit", function(){
					return confirm("Are you sure, you want to delete?");
						});

		$(function(){

				 $( "#getsender" ).autocomplete({	
				 	max:10,
					source: function (request, response) {
							 $.ajax({
								 url:  "{{route('senders.autocomplete',[Auth::id(),''])}}" + "/"+ request.term,
								 data:"",
								 dataType: "json",
								 success: response,
								 error: function () {
									 response([]);
									 
								 }
							 });
						 },
					select: function( event, ui ) {
						var add="{{route('senders.show',"")}}";		
					window.location.href = add+'/'+ui.item.id;
					}
    			});
				
			});
@endsection